spring:
  application:
    name: finance-feeder
  profiles:
    group:
      local:
        - yf
        - local-gcp
      stg:
        - yf
        - stg-gcp
      dark:
        - yf
        - dark-gcp
  messages:
    encoding: UTF-8
  web:
    locale: jp
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE_ENUMS_USING_TO_STRING: true

setting:
  feed:
    range: 1d
    interval: 1d
