spring:
  application:
    name: finance-feeder
  profiles:
    group:
      local:
        - yf
        - local-firestore
      stg:
        - yf
        - stg-firestore
    include:
      stg

setting:
  feed:
    range: 7d
    interval: 1d
